name: Update PR Spreadsheet
on:
  pull_request:
    types: [opened, reopened, edited, closed, synchronize, assigned, unassigned, review_requested, review_request_removed]
  pull_request_review:
    types: [submitted, edited, dismissed]
  issue_comment:
    types: [created, edited, deleted]

jobs:
  update-spreadsheet:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Checkout .github repository
      uses: actions/checkout@v4
      with:
        repository: learningequality/.github
        path: .github-repo

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install
      # working-directory: .github-repo

    - name: Run script
      env:
        SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        SHEET_NAME: ${{ secrets.SHEET_NAME }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        node script.js \
          "${{ github.event.pull_request.state }}" \
          "${{ github.event.pull_request.merged_at }}" \
          "${{ github.event.pull_request.html_url }}" \
          "${{ github.event.pull_request.user.login }}" \
          "${{ github.event.pull_request.title }}" \
          "${{ github.event.pull_request.base.repo.name }}" \
          "${{ github.event.pull_request.updated_at }}" \
          "${{ join(github.event.pull_request.requested_reviewers.*.login, ',') }}" \
          "${{ join(github.event.pull_request.assignees.*.login, ',') }}" \
          "${{ github.event.pull_request.user.site_admin }}" \
          "${{ github.event.pull_request.user.type }}" \
          "${{ github.event.pull_request.author_association }}"
